// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// firstWeightMatrix
NumericMatrix firstWeightMatrix(NumericMatrix Z);
RcppExport SEXP linearFeedbackModel_firstWeightMatrix(SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    __result = Rcpp::wrap(firstWeightMatrix(Z));
    return __result;
END_RCPP
}
// qMu
List qMu(NumericVector theta, IntegerMatrix idx, int nT, NumericMatrix data);
RcppExport SEXP linearFeedbackModel_qMu(SEXP thetaSEXP, SEXP idxSEXP, SEXP nTSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    __result = Rcpp::wrap(qMu(theta, idx, nT, data));
    return __result;
END_RCPP
}
// quasiDifference
NumericVector quasiDifference(NumericVector theta, IntegerMatrix idx, int nT, NumericMatrix data);
RcppExport SEXP linearFeedbackModel_quasiDifference(SEXP thetaSEXP, SEXP idxSEXP, SEXP nTSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    __result = Rcpp::wrap(quasiDifference(theta, idx, nT, data));
    return __result;
END_RCPP
}
// GMM
double GMM(NumericVector theta, IntegerMatrix idx, int nT, NumericMatrix data, NumericMatrix Z, NumericMatrix W_inv);
RcppExport SEXP linearFeedbackModel_GMM(SEXP thetaSEXP, SEXP idxSEXP, SEXP nTSEXP, SEXP dataSEXP, SEXP ZSEXP, SEXP W_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W_inv(W_invSEXP);
    __result = Rcpp::wrap(GMM(theta, idx, nT, data, Z, W_inv));
    return __result;
END_RCPP
}
// quasiDifference2
NumericVector quasiDifference2(NumericVector theta, IntegerMatrix idx, int nT, NumericMatrix data);
RcppExport SEXP linearFeedbackModel_quasiDifference2(SEXP thetaSEXP, SEXP idxSEXP, SEXP nTSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    __result = Rcpp::wrap(quasiDifference2(theta, idx, nT, data));
    return __result;
END_RCPP
}
// secondWeightMatrix
NumericMatrix secondWeightMatrix(NumericVector theta, IntegerMatrix idx, int nT, NumericMatrix data, NumericMatrix Z);
RcppExport SEXP linearFeedbackModel_secondWeightMatrix(SEXP thetaSEXP, SEXP idxSEXP, SEXP nTSEXP, SEXP dataSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    __result = Rcpp::wrap(secondWeightMatrix(theta, idx, nT, data, Z));
    return __result;
END_RCPP
}
