# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

firstWeightMatrix <- function(Z) {
    .Call('linearFeedbackModel_firstWeightMatrix', PACKAGE = 'linearFeedbackModel', Z)
}

qMu <- function(theta, idx, nT, data) {
    .Call('linearFeedbackModel_qMu', PACKAGE = 'linearFeedbackModel', theta, idx, nT, data)
}

quasiDifference <- function(theta, idx, nT, data) {
    .Call('linearFeedbackModel_quasiDifference', PACKAGE = 'linearFeedbackModel', theta, idx, nT, data)
}

GMM <- function(theta, idx, nT, data, Z, W_inv) {
    .Call('linearFeedbackModel_GMM', PACKAGE = 'linearFeedbackModel', theta, idx, nT, data, Z, W_inv)
}

quasiDifference2 <- function(theta, idx, nT, data) {
    .Call('linearFeedbackModel_quasiDifference2', PACKAGE = 'linearFeedbackModel', theta, idx, nT, data)
}

secondWeightMatrix <- function(theta, idx, nT, data, Z) {
    .Call('linearFeedbackModel_secondWeightMatrix', PACKAGE = 'linearFeedbackModel', theta, idx, nT, data, Z)
}

